// <auto-generated />
using System;
using AutocleanManager.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AutocleanManager.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260320230650_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AutocleanManager.Api.Models.Agendamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DirtLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.Property<int>("WashTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId");

                    b.HasIndex("WashTypeId");

                    b.ToTable("Agendamentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DirtLevel = "Pesada",
                            ScheduledAt = new DateTime(2026, 3, 20, 18, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Confirmado",
                            TotalPrice = 72m,
                            UserId = 1,
                            VehicleId = 1,
                            WashTypeId = 3
                        },
                        new
                        {
                            Id = 2,
                            DirtLevel = "Leve",
                            ScheduledAt = new DateTime(2026, 3, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Aguardando",
                            TotalPrice = 35m,
                            UserId = 1,
                            VehicleId = 2,
                            WashTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            DirtLevel = "Media",
                            ScheduledAt = new DateTime(2026, 3, 22, 14, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Na fila",
                            TotalPrice = 44m,
                            UserId = 2,
                            VehicleId = 3,
                            WashTypeId = 2
                        });
                });

            modelBuilder.Entity("AutocleanManager.Api.Models.TipoLavagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("numeric");

                    b.Property<int>("EstimatedDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TiposLavagem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 35m,
                            EstimatedDurationMinutes = 30,
                            Name = "Lavagem externa"
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 40m,
                            EstimatedDurationMinutes = 40,
                            Name = "Lavagem interna"
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 60m,
                            EstimatedDurationMinutes = 60,
                            Name = "Lavagem completa"
                        });
                });

            modelBuilder.Entity("AutocleanManager.Api.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "joao@email.com",
                            Name = "Joao Silva",
                            Role = "Cliente"
                        },
                        new
                        {
                            Id = 2,
                            Email = "ana@email.com",
                            Name = "Ana Martins",
                            Role = "Cliente"
                        },
                        new
                        {
                            Id = 3,
                            Email = "carlos@email.com",
                            Name = "Carlos Lima",
                            Role = "Funcionario"
                        });
                });

            modelBuilder.Entity("AutocleanManager.Api.Models.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Veiculos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Fiat",
                            Color = "Prata",
                            Model = "Argo",
                            Plate = "ABC1D23",
                            UserId = 1,
                            Year = 2021
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Honda",
                            Color = "Preto",
                            Model = "Civic",
                            Plate = "HIJ7K89",
                            UserId = 1,
                            Year = 2020
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Volkswagen",
                            Color = "Branco",
                            Model = "Polo",
                            Plate = "EFG4H56",
                            UserId = 2,
                            Year = 2022
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Toyota",
                            Color = "Cinza",
                            Model = "Corolla",
                            Plate = "LMN0P12",
                            UserId = 2,
                            Year = 2023
                        });
                });

            modelBuilder.Entity("AutocleanManager.Api.Models.Agendamento", b =>
                {
                    b.HasOne("AutocleanManager.Api.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutocleanManager.Api.Models.Veiculo", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutocleanManager.Api.Models.TipoLavagem", null)
                        .WithMany()
                        .HasForeignKey("WashTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AutocleanManager.Api.Models.Veiculo", b =>
                {
                    b.HasOne("AutocleanManager.Api.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
