// <auto-generated />
using System;
using AutocleanManager.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AutocleanManager.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AutocleanManager.Api.Models.Agendamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHoraAgendada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NivelSujeira")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecoTotal")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TipoLavagemId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TipoLavagemId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VeiculoId");

                    b.ToTable("Agendamentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataHoraAgendada = new DateTime(2026, 3, 20, 18, 0, 0, 0, DateTimeKind.Utc),
                            NivelSujeira = "Pesada",
                            PrecoTotal = 72m,
                            Status = "Confirmado",
                            TipoLavagemId = 3,
                            UsuarioId = 1,
                            VeiculoId = 1
                        },
                        new
                        {
                            Id = 2,
                            DataHoraAgendada = new DateTime(2026, 3, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            NivelSujeira = "Leve",
                            PrecoTotal = 35m,
                            Status = "Aguardando",
                            TipoLavagemId = 1,
                            UsuarioId = 1,
                            VeiculoId = 2
                        },
                        new
                        {
                            Id = 3,
                            DataHoraAgendada = new DateTime(2026, 3, 22, 14, 0, 0, 0, DateTimeKind.Utc),
                            NivelSujeira = "Media",
                            PrecoTotal = 44m,
                            Status = "Na fila",
                            TipoLavagemId = 2,
                            UsuarioId = 2,
                            VeiculoId = 3
                        });
                });

            modelBuilder.Entity("AutocleanManager.Api.Models.TipoLavagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DuracaoEstimadaMinutos")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecoBase")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("TiposLavagem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DuracaoEstimadaMinutos = 30,
                            Nome = "Lavagem externa",
                            PrecoBase = 35m
                        },
                        new
                        {
                            Id = 2,
                            DuracaoEstimadaMinutos = 40,
                            Nome = "Lavagem interna",
                            PrecoBase = 40m
                        },
                        new
                        {
                            Id = 3,
                            DuracaoEstimadaMinutos = 60,
                            Nome = "Lavagem completa",
                            PrecoBase = 60m
                        });
                });

            modelBuilder.Entity("AutocleanManager.Api.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "joao@email.com",
                            Nome = "Joao Silva",
                            Papel = "Cliente"
                        },
                        new
                        {
                            Id = 2,
                            Email = "ana@email.com",
                            Nome = "Ana Martins",
                            Papel = "Cliente"
                        },
                        new
                        {
                            Id = 3,
                            Email = "carlos@email.com",
                            Nome = "Carlos Lima",
                            Papel = "Funcionario"
                        });
                });

            modelBuilder.Entity("AutocleanManager.Api.Models.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Ano")
                        .HasColumnType("integer");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Veiculos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ano = 2021,
                            Cor = "Prata",
                            Marca = "Fiat",
                            Modelo = "Argo",
                            Placa = "ABC1D23",
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            Ano = 2020,
                            Cor = "Preto",
                            Marca = "Honda",
                            Modelo = "Civic",
                            Placa = "HIJ7K89",
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 3,
                            Ano = 2022,
                            Cor = "Branco",
                            Marca = "Volkswagen",
                            Modelo = "Polo",
                            Placa = "EFG4H56",
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 4,
                            Ano = 2023,
                            Cor = "Cinza",
                            Marca = "Toyota",
                            Modelo = "Corolla",
                            Placa = "LMN0P12",
                            UsuarioId = 2
                        });
                });

            modelBuilder.Entity("AutocleanManager.Api.Models.Agendamento", b =>
                {
                    b.HasOne("AutocleanManager.Api.Models.TipoLavagem", null)
                        .WithMany()
                        .HasForeignKey("TipoLavagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutocleanManager.Api.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutocleanManager.Api.Models.Veiculo", null)
                        .WithMany()
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AutocleanManager.Api.Models.Veiculo", b =>
                {
                    b.HasOne("AutocleanManager.Api.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
